### ISSUE TITLE
EDA issues

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/DSCI_522-Group-403-Student-Performance#39]
- What are the main takeaways from your EDA? You have many figures but you should summarize what you learned about the dataset.
- Do not use point form to write. Write complete paragraphs to create a narrative about your data.

**Comment by kfoofw** [comment]
Hi @yavyx 

Our initial EDA had some general pointers, but we went through individual feature comparisons against the response variable. Each individual graph had a short sentence with observation and potential hypothesis on the individual feature plot (no point form here).

Since our topic is to find the top 5 predictors out of all features, our EDA had to serve that purpose and we felt that comparing all indivdual feature plots was necessary since it will be unfair to leave any out.

For reference, see the rectangles with text analysis explanation/narrative for each feature plot.
![snapshot](https://user-images.githubusercontent.com/7871453/73119367-a4cd4300-3f15-11ea-9182-bb1995f41b85.png)

For your easy reference, the EDA notebook can be found [here](https://github.com/UBC-MDS/DSCI_522-Group-403-Student-Performance/blob/v0.1/src/EDA.ipynb)
